version: 1.0.{build}
configuration: Debug
platform: Any CPU
build:
  parallel: true
  verbosity: minimal
notifications:
- provider: Email
  to:
  - ralms@ralms.net
  on_build_success: true
  on_build_failure: false
  on_build_status_changed: false
